### ISSUE TITLE
[BUG] Group migrated to Supergroup

### ISSUE THREAD

**Issue by Grufoony** [RiccardoBarbieri/the_unibot#22]
Autosend does not work if a group has migrated to a supergroup (whatever that means).

For @RiccardoBarbieri , you can check logs 17/09/2023 20:30:06.

This bug has high priority.

**Comment by Grufoony** [comment]
Can you upload a log?

**Comment by RiccardoBarbieri** [comment]
> Can you upload a log? @RiccardoBarbieri

Sep 16 22:30:04 ubuntu python[30200]: 2023-09-16 22:30:04,393 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Sep 16 22:30:04 ubuntu python[30200]: Traceback (most recent call last):
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 800, in _run
Sep 16 22:30:04 ubuntu python[30200]:     await self.callback(context)
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/./bot/bot.py", line 931, in __callback_loop
Sep 16 22:30:04 ubuntu python[30200]:     await self.__orario_autosend(context)
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/./bot/bot.py", line 901, in __orario_autosend
Sep 16 22:30:04 ubuntu python[30200]:     await context.bot.send_message(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 2613, in send_message
Sep 16 22:30:04 ubuntu python[30200]:     return await super().send_message(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 394, in decorator
Sep 16 22:30:04 ubuntu python[30200]:     result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 820, in send_message
Sep 16 22:30:04 ubuntu python[30200]:     return await self._send_message(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 517, in _send_message
Sep 16 22:30:04 ubuntu python[30200]:     result = await super()._send_message(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 572, in _send_message
Sep 16 22:30:04 ubuntu python[30200]:     result = await self._post(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 482, in _post
Sep 16 22:30:04 ubuntu python[30200]:     return await self._do_post(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 335, in _do_post
Sep 16 22:30:04 ubuntu python[30200]:     return await super()._do_post(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 510, in _do_post
Sep 16 22:30:04 ubuntu python[30200]:     return await request.post(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 168, in post
Sep 16 22:30:04 ubuntu python[30200]:     result = await self._request_wrapper(
Sep 16 22:30:04 ubuntu python[30200]:   File "/home/ubuntu/the_unibot/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 308, in _request_wrapper
Sep 16 22:30:04 ubuntu python[30200]:     raise ChatMigrated(migrate_to_chat_id)
Sep 16 22:30:04 ubuntu python[30200]: telegram.error.ChatMigrated: Group migrated to supergroup. New chat id: -1001887208883
Sep 16 22:30:04 ubuntu python[30200]: 2023-09-16 22:30:04,409 - apscheduler.executors.default - INFO - Job "__callback_loop (trigger: interval[1 day, 0:00:00], next run at: 2023-09-17 20:29:59 UTC)" executed successfully
